"""
planner.py - LLM-Powered Recipe Generator (NIM REST Edition)

Converts user prompts into executable Recipe Schema v2.0 DAGs.
Uses NVIDIA NIM (llama-3.1-8b-instruct) via raw HTTP and strict JSON Schema enforcement.

Author: Quanta Box Paradox Engineering
Version: 3.0.0
"""

import os
import json
import logging
import asyncio
import time
from typing import Any, Dict, List, Optional
import uuid
from datetime import datetime, timezone
from pydantic import BaseModel, ValidationError, Field

from core.utils.httpclient import GetClient
from core.recipe.recipeSchema import Recipe, RecipeMetadata, Node, Edge, ExitPoints, Action, ActionType, NodeType, ExecutionConfig

logger = logging.getLogger("planner")

# =============================================================================
# MODELS (Micro-Schema)
# =============================================================================

class ActionIntent(BaseModel):
    """
    Minimal representation of a browser action for token efficiency.
    """
    action: str  # CLICK, TYPE, EXTRACT, etc.
    semantic_anchors: list[str] = Field(default_factory=list)  # 4-6 synonyms/contextual clues for vector search
    value: Optional[str] = None  # Text to type or value to select
    timeout: Optional[int] = None

class MicroPlan(BaseModel):
    """
    The 'Soft Recipe' generated by the LLM.
    Focuses only on strategic subtasks.
    """
    subtasks: list[ActionIntent]

# =============================================================================
# RESULT TYPE (Legacy support)
# =============================================================================

from dataclasses import dataclass

@dataclass
class PlannerResult:
    """Result of recipe generation (Legacy support for RAG orchestrator)."""
    success: bool
    recipe: Optional[Dict] = None
    error: Optional[str] = None
    generation_ms: int = 0
    model_used: str = "meta/llama-3.1-8b-instruct"
    tokens_used: int = 0

# =============================================================================
# CONFIGURATION
# =============================================================================

NIM_API_URL = "https://integrate.api.nvidia.com/v1/chat/completions"
NIM_MODEL = "meta/llama-3.1-8b-instruct"
MAX_RETRIES = 3

class CompilationFailedError(Exception):
    """Raised when the LLM fails to generate a valid recipe after multiple retries."""
    pass

from core.rag.prompts import PLANNER_SYSTEM_PROMPT

# =============================================================================
# MODELS
# =============================================================================

# =============================================================================
# DAG COMPILER
# =============================================================================

def compile_recipe_from_microplan(plan: MicroPlan, context: str) -> Recipe:
    nodes = []
    edges = []

    # 1. Generate System Boilerplate natively in Python
    recipe_id = f"rec_{uuid.uuid4().hex[:8]}"
    name = "Auto-generated"
    if "objective" in context.lower():
        # Quick extract for naming
        name = f"Auto-generated: {context[:40]}"

    metadata = RecipeMetadata(
        id=recipe_id,
        name=name,
        created_at=datetime.now(timezone.utc)
    )

    # 2. Translate Intents to Nodes and Link Edges deterministically
    previous_node_id = None
    entry_point = None

    for idx, intent in enumerate(plan.subtasks):
        node_id = f"node_{idx}"
        if idx == 0:
            entry_point = node_id

        # Map basic types to ActionType enum
        action_map = {
            "NAVIGATE": ActionType.NAVIGATE,
            "CLICK": ActionType.CLICK,
            "DOUBLECLICK": ActionType.CLICK,
            "TYPE": ActionType.TYPE,
            "PRESS_ENTER": ActionType.TYPE,
            "EXTRACT": ActionType.EXTRACT,
            "EXTRACT_TABLE": ActionType.EXTRACT_TABLE,
            "WAIT": ActionType.WAIT,
            "WAIT_HIDDEN": ActionType.WAIT_HIDDEN,
            "SCREENSHOT": ActionType.SCREENSHOT,
            "SCROLL": ActionType.SCROLL,
            "HOVER": ActionType.HOVER,
            "SELECT": ActionType.SELECT,
            "CHECK": ActionType.CHECK,
        }

        mapped_type = action_map.get(intent.action.upper(), ActionType.CLICK)

        # Combine Semantic Anchors into a single dense string for the transformer
        # This solves the "Semantic Surface Area" problem
        semantic_target = ", ".join(intent.semantic_anchors) if intent.semantic_anchors else "Element"

        # Build your heavy Node structure here using Python, not AI
        action = Action(
            seq=1,
            type=mapped_type,
            intent=semantic_target,
            value=intent.value,
        )

        node = Node(
            id=node_id,
            name=intent.action,
            type=NodeType.ACTION,
            execution=ExecutionConfig(timeout_ms=30000),
            actions=[action]
        )
        nodes.append(node)

        if previous_node_id:
            edges.append(Edge(source=previous_node_id, target=node_id))
        previous_node_id = node_id

    # 3. Define standard exit points
    # Fallback if no nodes
    if not previous_node_id:
        previous_node_id = "node_end"
        entry_point = previous_node_id

    exit_points = ExitPoints(
        success=previous_node_id, # Last node is success
        failure="global_error_handler",
        timeout="global_timeout_handler"
    )

    return Recipe(
        metadata=metadata,
        nodes=nodes,
        edges=edges,
        entry_point=entry_point or "node_end",
        exit_points=exit_points
    )

# =============================================================================
# PLANNER CLASS
# =============================================================================

class RecipePlanner:
    """
    LLM-Powered Recipe Generator using NVIDIA NIM REST API.
    Enforces strict structured outputs via Pydantic model_json_schema.
    """

    def __init__(self):
        self.api_key = os.getenv("NVIDIA_API_KEY")
        if not self.api_key:
            logger.warning("[Planner] NVIDIA_API_KEY is missing. Requests will fail.")

    async def generate_with_retry(
        self,
        prompt: str,
        url: str,
        classification: Optional[Dict] = None,
        job_id: Optional[str] = None
    ) -> Recipe:
        """
        Main entry point with autonomous retry loop and self-correction.
        """
        messages = [
            {"role": "system", "content": PLANNER_SYSTEM_PROMPT},
            {"role": "user", "content": self._build_user_message(prompt, url, classification)}
        ]

        # Generate JSON Schema from Pydantic Model
        microplan_schema = MicroPlan.model_json_schema()

        response_format = {
            "type": "json_schema",
            "json_schema": {
                "name": "microplan",
                "schema": microplan_schema,
                "strict": True
            }
        }

        attempts = 0
        while attempts < MAX_RETRIES:
            attempts += 1
            logger.info(f"[Planner] Generation attempt {attempts}/{MAX_RETRIES}")

            try:
                # 1. Raw HTTP Request via Global Singleton Client
                response_content = await self._call_nim(messages, response_format)

                # 2. Local Pydantic Gatekeeping (Validation)
                try:
                    logger.info(f"[Planner] LLM output received: len={len(response_content)}")

                    # BEST POSSIBLE FIX: Markdown/Conversational Stripper
                    # Extracts the raw JSON object directly from the LLM output buffer
                    clean_content = response_content
                    start_idx = clean_content.find('{')
                    end_idx = clean_content.rfind('}')
                    if start_idx != -1 and end_idx != -1 and end_idx >= start_idx:
                        clean_content = clean_content[start_idx:end_idx+1]
                    else:
                        clean_content = clean_content.strip()

                    micro_plan = MicroPlan.model_validate_json(clean_content)

                    # 3. Python builds the massive DAG
                    recipe = compile_recipe_from_microplan(micro_plan, prompt)

                    logger.info(f"✅ [Planner] Successfully compiled recipe: {recipe.metadata.name}")

                    # TELEMETRY INJECTION
                    if job_id:
                        from core.NervousSystem import NervousSystem
                        telemetry_payload = json.dumps({
                            "type": "log",
                            "message": f"[Planner] Compiled DAG: {recipe.model_dump_json()}"
                        })
                        await NervousSystem.publish(f"quanta.telemetry.{job_id}", telemetry_payload)

                    return recipe

                except ValidationError as ve:
                    error_details = ve.json(indent=2)
                    logger.warning(f"❌ [Planner] Pydantic Validation Failed (Attempt {attempts})")
                    logger.error(f"[Planner] Validation Errors: {error_details}")
                    logger.error(f"[Planner] LLM Output: {response_content}")

                    # 4. Feed Error Back to LLM for Self-Correction
                    messages.append({"role": "assistant", "content": response_content})
                    messages.append({
                        "role": "user",
                        "content": f"JSON validation failed. Fix these exact schema errors:\n{error_details}"
                    })
                    continue

            except Exception as e:
                logger.error(f"[Planner] API or Network Error: {e}")
                if attempts >= MAX_RETRIES:
                    raise CompilationFailedError(f"HTTP/API failure after {MAX_RETRIES} attempts: {e}")
                await asyncio.sleep(1) # Tiny backoff

        raise CompilationFailedError(f"Exhausted {MAX_RETRIES} attempts. LLM failed to produce a valid schema.")

    async def generate(
        self,
        prompt: str,
        url: str,
        classification: Optional[Dict] = None,
        similar_template: Optional[Dict] = None,
        job_id: Optional[str] = None
    ) -> PlannerResult:
        """
        Orchestration wrapper for Preflight pipeline.
        """
        start_time = time.time()
        try:
            recipe = await self.generate_with_retry(prompt, url, classification, job_id=job_id)
            duration = int((time.time() - start_time) * 1000)
            return PlannerResult(
                success=True,
                recipe=recipe.model_dump(),
                generation_ms=duration
            )
        except Exception as e:
            logger.error(f"[Planner] Generation failed: {e}")
            return PlannerResult(
                success=False,
                error=str(e),
                generation_ms=int((time.time() - start_time) * 1000)
            )

    async def _call_nim(self, messages: list[dict[str, str]], response_format: Dict) -> str:
        """Execute raw HTTP request to NVIDIA NIM API."""
        client = GetClient()

        payload = {
            "model": NIM_MODEL,
            "messages": messages,
            "temperature": 0.1,
            "response_format": response_format
        }

        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.api_key}"
        }

        response = await client.post(NIM_API_URL, json=payload, headers=headers)

        if response.status_code != 200:
            logger.error(f"[Planner] NIM API Error: {response.text}")
            response.raise_for_status()

        data = response.json()
        return data["choices"][0]["message"]["content"]

    def _build_user_message(self, prompt: str, url: str, classification: Optional[Dict]) -> str:
        """Formats the user context for the LLM."""
        context = f"## TARGET URL\n{url}\n\n## USER REQUEST\n{prompt}\n"
        if classification:
            context += f"\n## PAGE CONTEXT\n{json.dumps(classification, indent=2)}"

        context += "\n\nGenerate the Recipe DAG JSON now."
        return context

# =============================================================================
# SINGLETON
# =============================================================================

_planner_instance: Optional[RecipePlanner] = None

def get_planner() -> RecipePlanner:
    """Get singleton planner instance."""
    global _planner_instance
    if _planner_instance is None:
        _planner_instance = RecipePlanner()
    return _planner_instance
