"""
domHarvester.py — Full-Document DOM Snapshot Engine

REPLACES: actionMap.py / ActionMapBuilder
PURPOSE:  Loads the entire DOM via the enhanced extractor.js, then applies
          Python-side post-processing: sorting by visibility, validating
          element counts, and grouping elements by their container zone
          (header, nav, main, aside, footer) to give the ElementMatcher
          spatial context with zero additional browser calls.

DESIGN:
  - Zero scroll: reads all elements across the full document in ONE evaluate() call.
  - Post-processing is pure Python — no browser round-trips.
  - Returns a DOMSnapshot dataclass that the ElementMatcher and NodeBuilder consume.
"""

import asyncio
import logging
import os
import time
from dataclasses import dataclass, field
from typing import List, Optional, Dict

from playwright.async_api import Page

logger = logging.getLogger("domHarvester")


# ─── DATA CLASSES ─────────────────────────────────────────────────────────────

@dataclass
class DOMElement:
    """
    Represents one interactive element extracted from the full DOM.
    All fields map directly to the extractor.js output schema.
    """
    qId: str                          # e.g. "q-14" — Quanta tracking ID injected into DOM
    tag: str                          # Lowercase HTML tag (button, input, a …)
    fingerprint: str                  # e.g. "button|submit|sign in" — for deduplication

    # Visibility / position
    isVisible: bool     = True
    inViewport: bool    = False        # Is currently on screen
    scrollY: int        = 0            # Absolute Y from document top — we scroll here at exec time
    scrollX: int        = 0
    width: int          = 0
    height: int         = 0

    # Source context
    inShadowDom: bool   = False
    inIframe: bool      = False
    iframeIndex: Optional[int] = None

    # Semantic attributes — all Optional; absent = not on this element
    text: Optional[str]          = None
    ariaLabel: Optional[str]     = None
    ariaLabelledBy: Optional[str]= None
    placeholder: Optional[str]   = None
    name: Optional[str]          = None
    id: Optional[str]            = None
    dataTestId: Optional[str]    = None
    href: Optional[str]          = None
    value: Optional[str]         = None
    itemprop: Optional[str]      = None
    title: Optional[str]         = None
    type: Optional[str]          = None
    role: Optional[str]          = None
    classes: list[str]           = field(default_factory=list)

    # XPath — generated by extractor.js inside V8 (e.g. "/html/body/div[2]/main/form/button")
    xpath: str = ""

    # Zone assigned during post-processing (header/nav/main/aside/footer/unknown)
    zone: str = "unknown"


@dataclass
class DOMSnapshot:
    """
    The complete result of a page harvest.
    Passed directly to ElementMatcher for offline planning.
    """
    url: str
    elements: list[DOMElement]
    harvestDurationMs: int
    pageTitle: str
    totalExtracted: int          # Raw count before dedup (for diagnostics)
    timestamp: float = field(default_factory=time.time)

    @property
    def inViewportElements(self) -> list[DOMElement]:
        """Convenience: elements currently on screen."""
        return [el for el in self.elements if el.inViewport]

    @property
    def belowFoldElements(self) -> list[DOMElement]:
        """Convenience: elements that need scrolling to reach."""
        return [el for el in self.elements if not el.inViewport]

    def getElementsByZone(self, zone: str) -> list[DOMElement]:
        """Returns all elements in a named page zone (header, main, etc.)."""
        return [el for el in self.elements if el.zone == zone]

    def toDict(self) -> dict:
        """Serializes to a plain dict for passing over Temporal activity boundaries."""
        return {
            "url": self.url,
            "elements": [el.__dict__ for el in self.elements],
            "harvestDurationMs": self.harvestDurationMs,
            "pageTitle": self.pageTitle,
            "totalExtracted": self.totalExtracted,
            "timestamp": self.timestamp,
        }

    @classmethod
    def fromDict(cls, d: dict) -> "DOMSnapshot":
        """Deserializes from a plain dict (after crossing Temporal boundary)."""
        elements = [DOMElement(**el) for el in d.get("elements", [])]
        return cls(
            url=d["url"],
            elements=elements,
            harvestDurationMs=d.get("harvestDurationMs", 0),
            pageTitle=d.get("pageTitle", ""),
            totalExtracted=d.get("totalExtracted", len(elements)),
            timestamp=d.get("timestamp", time.time()),
        )


# ─── ZONE DETECTION ───────────────────────────────────────────────────────────

# Heuristic Y-boundaries (as a fraction of total page height)
# These are tuned for typical long-scrolling web pages.
ZONE_BOUNDARIES = {
    "header": (0.0, 0.08),    # Top 8% of page
    "nav":    (0.0, 0.12),    # Navigation overlaps with header
    "main":   (0.08, 0.80),   # Core content zone
    "aside":  (0.25, 0.75),   # Sidebar (we can't detect this from Y alone — approximation)
    "footer": (0.80, 1.0),    # Bottom 20%
}

def _assignZone(element: DOMElement, pageHeight: int) -> str:
    """
    Assigns a semantic zone to an element based on its absolute Y position.
    Falls back to "unknown" if the page height is not available.
    This is used by the ElementMatcher's positional heuristic scoring.
    """
    if pageHeight <= 0:
        return "unknown"

    ratio = element.scrollY / pageHeight

    # Check from smallest zone first (header takes priority over nav)
    if ratio <= 0.08:
        return "header"
    elif ratio >= 0.80:
        return "footer"
    elif ratio <= 0.15:
        return "nav"
    else:
        return "main"


# ─── DOM HARVESTER ────────────────────────────────────────────────────────────

class DOMHarvester:
    """
    Single-pass full-document DOM extractor.

    Usage:
        harvester = DOMHarvester(page)
        snapshot  = await harvester.harvest("https://example.com")
    """

    def __init__(self, page: Page):
        self.page = page
        self._scriptCache: Optional[str] = None

    async def harvest(self, url: str = None) -> DOMSnapshot:
        """
        Main entry point. Optionally navigates to `url`, then runs the full
        extractor.js against the current DOM and returns a DOMSnapshot.

        Args:
            url: If provided, navigates before harvesting. If None, harvests
                 the current page state (useful for mid-flow re-harvests).
        """
        startTime = time.monotonic()

        # Navigate if a URL was given
        if url:
            await self._navigateTo(url)

        # Collect page metadata
        pageTitle = await self.page.title()

        # Get the full document height for zone assignment
        pageHeight = await self.page.evaluate(
            "() => document.documentElement.scrollHeight"
        )

        # Evaluate the full-document extractor script
        rawElements = await self._runExtractor()
        totalExtracted = len(rawElements)

        # Convert raw dicts to DOMElement dataclasses
        elements = []
        for raw in rawElements:
            try:
                el = self._parseRawElement(raw)
                el.zone = _assignZone(el, pageHeight)
                elements.append(el)
            except Exception as exc:
                logger.warning(f"[DOMHarvester] Skipped malformed element: {exc}")

        # Sort: in-viewport first, then by absolute Y position (top → bottom)
        elements.sort(key=lambda e: (0 if e.inViewport else 1, e.scrollY))

        elapsedMs = int((time.monotonic() - startTime) * 1000)

        # ─── ANTI-BOT FIREWALL DETECTION ─────────────────────────────────────
        if totalExtracted < 10:
            try:
                html = await self.page.content()
                if "challenge-container" in html or "AwsWafIntegration" in html:
                    logger.warning("[DOMHarvester] AWS WAF Captcha detected.")
                    raise Exception("Target website (Amazon/AWS) explicitly blocked the headless browser via WAF Captcha. Request requires anti-detect residential proxies.")
                if "cf-browser-verification" in html or "cloudflare" in html.lower():
                    logger.warning("[DOMHarvester] Cloudflare Turnstile detected.")
                    raise Exception("Target website has Cloudflare anti-bot protection enabled which blocked the connection.")
            except Exception as e:
                if "explicitly blocked" in str(e) or "protection enabled" in str(e):
                    raise
                pass

        logger.info(
            f"[DOMHarvester] Harvested {len(elements)} elements "
            f"(raw: {totalExtracted}) in {elapsedMs}ms | "
            f"viewport: {sum(1 for e in elements if e.inViewport)} | "
            f"below-fold: {sum(1 for e in elements if not e.inViewport)}"
        )

        return DOMSnapshot(
            url=url or self.page.url,
            elements=elements,
            harvestDurationMs=elapsedMs,
            pageTitle=pageTitle,
            totalExtracted=totalExtracted,
        )

    async def reHarvest(self) -> DOMSnapshot:
        """
        Re-harvests the current page state without navigating.
        Called after an action that mutates the DOM (e.g., button click that
        opens a modal, or SPA navigation that swaps page content).
        """
        return await self.harvest(url=None)

    # ── PRIVATE METHODS ────────────────────────────────────────────────────

    async def _navigateTo(self, url: str):
        """
        Navigate with a sensible timeout strategy:
          1. Wait for DOM content (fast, works for SSR pages)
          2. Attempt networkidle (good for SPAs — may time out on heavy pages)
          3. Short settle window for JS frameworks to paint
        """
        try:
            await self.page.goto(url, wait_until="domcontentloaded", timeout=30000)
        except Exception as navErr:
            logger.warning(f"[DOMHarvester] Navigation warning: {navErr}")

        try:
            # networkidle catches React/Vue/Angular hydration
            await self.page.wait_for_load_state("networkidle", timeout=7000)
        except Exception:
            # Heavy pages (many ads, analytics) may never reach networkidle — that's OK
            pass

        # Fixed settle window for frameworks that animate their initial render
        await asyncio.sleep(1.5)

    async def _runExtractor(self) -> list[dict]:
        """
        Loads extractor.js from disk (cached), evaluates it in the browser,
        and returns the raw array of element descriptors.
        """
        script = self._loadExtractorScript()
        try:
            # Wrap the script in an IIFE, removing any trailing semicolon to avoid SyntaxError
            clean_script = script.strip().rstrip(';')
            result = await self.page.evaluate(f"({clean_script})()")
            
            if not isinstance(result, list):
                logger.warning(f"[DOMHarvester] Result is NOT a list! Type: {type(result)} | Value: {str(result)[:200]}")
                return []
            
            # Additional debug logging
            if len(result) == 0:
                html = await self.page.content()
                try:
                    body = await self.page.evaluate("document.body.innerHTML")
                    logger.warning(f"[DOMHarvester] Returned empty list. Page URL: {self.page.url} | HTML Length: {len(html)} | Body: {body[:800]}")
                except Exception as e:
                    logger.warning(f"[DOMHarvester] Returned empty list. Page URL: {self.page.url} | HTML Length: {len(html)} | Body eval error: {e}")
                
            return result
        except Exception as exc:
            logger.error(f"[DOMHarvester] extractor.js evaluation failed: {exc}")
            return []

    def _loadExtractorScript(self) -> str:
        """Reads extractor.js from disk (cached after first load)."""
        if self._scriptCache:
            return self._scriptCache

        scriptDir  = os.path.dirname(os.path.abspath(__file__))
        scriptPath = os.path.join(scriptDir, "extractor.js")

        try:
            with open(scriptPath, "r", encoding="utf-8") as f:
                self._scriptCache = f.read()
            return self._scriptCache
        except FileNotFoundError:
            logger.critical(
                "[DOMHarvester] extractor.js not found! "
                f"Expected path: {scriptPath}"
            )
            # Return a minimal fallback so the workflow doesn't hard-crash
            return '() => []'

    @staticmethod
    def _parseRawElement(raw: dict) -> DOMElement:
        """
        Converts a raw dict from extractor.js into a typed DOMElement.
        Any missing fields fall back to the dataclass defaults.
        """
        return DOMElement(
            qId          = raw["qId"],
            tag          = raw.get("tag", ""),
            fingerprint  = raw.get("fingerprint", ""),
            isVisible    = raw.get("isVisible", True),
            inViewport   = raw.get("inViewport", False),
            scrollY      = raw.get("scrollY", 0),
            scrollX      = raw.get("scrollX", 0),
            width        = raw.get("width", 0),
            height       = raw.get("height", 0),
            inShadowDom  = raw.get("inShadowDom", False),
            inIframe     = raw.get("inIframe", False),
            iframeIndex  = raw.get("iframeIndex"),
            text         = raw.get("text"),
            ariaLabel    = raw.get("ariaLabel"),
            ariaLabelledBy=raw.get("ariaLabelledBy"),
            placeholder  = raw.get("placeholder"),
            name         = raw.get("name"),
            id           = raw.get("id"),
            dataTestId   = raw.get("dataTestId"),
            href         = raw.get("href"),
            value        = raw.get("value"),
            title        = raw.get("title"),
            type         = raw.get("type"),
            role         = raw.get("role"),
            classes      = raw.get("classes", []),
            xpath        = raw.get("xpath", ""),
        )
